[nexus] mark schema tests as heavy, increase timeout for one of them (#4832)
On my Linux machine, when running the tests in test_all, I'm starting to
see
`integration_tests::schema::nexus_applies_update_on_boot`
fail because of a 60s timeout waiting for nexus to start. The failure is
caused
due to contention -- the logs just seem to indicate each schema version
taking
5-15 seconds to apply.

To address this, do two things:

1. Mark the tests as heavy so that they run with less contention.
2. Increase the timeout for this specific test to 120s.

In the future, we may want to do something more clever like breaking
this test
up into several smaller ones.

Error message:

```
thread 'integration_tests::schema::nexus_applies_update_on_boot' panicked at nexus/tests/integration_tests/schema.rs:484:5:
Nexus should have started
```

Logs:
https://gist.github.com/sunshowers/39ee99badc5f75c2a3154ea602aa95aa