Update git dependencies and pin revisions
Change one of the dice-util dependencies so that it refers to a specific
pinned revision (copying the one in Cargo.lock) instead of a branch.

before:

```
$ cargo tree -i dice-verifier
error: specification `dice-verifier` is ambiguous
help: re-run this command with one of the following specifications
  git+https://github.com/oxidecomputer/dice-util?branch=main#dice-verifier@0.3.0-pre0
  git+https://github.com/oxidecomputer/dice-util?rev=4a39ef08d81e5177edee0bddb1146032aa21074d#dice-verifier@0.3.0-pre0
```

after:

```
$ cargo tree -i dice-verifier
error: specification `dice-verifier` is ambiguous
help: re-run this command with one of the following specifications
  git+https://github.com/oxidecomputer/dice-util?rev=4a39ef08d81e5177edee0bddb1146032aa21074d#dice-verifier@0.3.0-pre0
  git+https://github.com/oxidecomputer/dice-util?rev=ff9f27aa0d6ef6fb64c349890b6e3c242ea3d8fc#dice-verifier@0.3.0-pre0
```

Update management-gateway-service to the latest rev to pull in the
latest hubtools. Also update package-manifest.toml rev and sha256
accordingly. This pulled in some new `SpHandler trait functions that
needed implementing, so fill those in.

Also update to the latest hubtools.