[reconfigurator] Executor: only do cleanup for zones that are `ready_for_cleanup` (#7713)
Changes the three steps that required the earlier `PUT /omicron-zones`
execution step to succeed because they needed to clean up after zones
that were definitely shut down to now ready the `ready_for_cleanup`
blueprint disposition (which is set by the _planner_ after it confirms
via inventory that the zones are dead).

While I was here, I removed both the special case error-to-warning
implementation in a couple of steps and the `finalize` step that
compiled those. I believe all of that predates the ability for `omdb` to
interpret the update-engine event report. Now that it can, emitting step
warnings directly is fine. I spun this branch up in a4x2 and then shut
down one of the sled-agents; that results in this report the executor:

```
  last completed activation: iter 47, triggered by a periodic timer firing
    started at 2025-03-03T19:49:51.027Z (23s ago) and ran for 11711ms
    target blueprint: 3680509e-77c3-4d98-a8a4-276de89b2c53                                                                                                                                                                                                       
    execution:        enabled                                                                                                                                                                                                                                    
    status:           completed (15 steps)                                                                                                                                                                                                                       
    warning:          at: Plumb service firewall rules: failed to plumb service firewall rules to sleds: Internal Error: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/vpc/001de000-074c-4000-8000-000000000000/firewall/rules)
    warning:          at: Deploy Omicron zones: Failed to put OmicronZonesConfig {                                                                                                                                             

... snip the OmicronZonesConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-zones): error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-zones): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    warning:          at: Deploy datasets: Failed to put DatasetsConfig {                                                                                                                                              

... snip the DatasetConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/datasets): error sending request for url (http://[fd00:1122:3344:102::1]:12345/datasets): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    warning:          at: Deploy physical disks: Failed to put BlueprintPhysicalDisksConfig {                                                                                                                                              

... snip the BlueprintPhysicalDisksConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-physical-disks): error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-physical-disks): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    error:            (none)                                                                                                                                                                                                                                     
```

Closes #6999, under the assumption that as of this PR we've identified
all the inter-step dependencies and broken them.