[reconfigurator-cli] Fix blueprint-edit failing if there are multiple expunged zones with the same external IP (#7307)
I tried to reproduce #7305 using just reconfigurator-cli's simulated
example system. This required one change (adding external DNS zones,
db90b4a6528edb84e7d6095170c5a3646956fad6), and while I was here I
smoothed over a couple of minor ergonomic annoyances
(275e24e115059eb5ae9ca5dd5635d133596bf173 is uncontroversial, I hope,
and a147954743afc15ff0f73c306c0ff2c4c62ad7ae which is a little less
clearly good - happy to back this one out if folks don't like it).

With these changes, I can get to a reproduction:

```
generated RNG seed: discernibly-adaptive-grison
〉load-example
loaded example system with:
- collection: ed006741-bed9-4fd1-87e7-26c95a6f4dd9
- blueprint: 72183372-6429-4ab7-af83-5fea1a40bbcf
〉blueprint-show 72183372-6429-4ab7-af83-5fea1a40bbcf
... snip, finding an external DNS zone to expunge ...
〉blueprint-edit 72183372-6429-4ab7-af83-5fea1a40bbcf expunge-zone 34feb176-1129-4ca8-8df8-6e6cb1be2173
blueprint 9a5f95b4-7eb7-4b8d-b953-5fc9f403f330 created from blueprint 72183372-6429-4ab7-af83-5fea1a40bbcf: expunged zone 34feb176-1129-4ca8-8df8-6e6cb1be2173 from sled e78b0535-959d-4ba9-8d8c-ac3d591fc490
〉blueprint-plan 9a5f95b4-7eb7-4b8d-b953-5fc9f403f330
... snip, finding the ID of the newly-generated blueprint ...
〉blueprint-diff 9a5f95b4-7eb7-4b8d-b953-5fc9f403f330 0a054c71-82cb-4589-afa3-09ced1e425b9
... snip, finding the ID of the newly-added external DNS zone ...
〉blueprint-edit 0a054c71-82cb-4589-afa3-09ced1e425b9 expunge-zone 900df298-9c72-4a64-a4a7-7a92b722f68c
error: adding omicron zone external IP: associating Omicron zone 900df298-9c72-4a64-a4a7-7a92b722f68c with Floating(OmicronZoneExternalFloatingIp { id: 1c962069-7ced-4162-a11f-acb40fd954f4 (external_ip), ip: 198.51.100.3 }) failed due to duplicates: duplicate entry: OmicronZoneExternalIpEntry { zone_id: 900df298-9c72-4a64-a4a7-7a92b722f68c (service), ip: Floating(OmicronZoneExternalFloatingIp { id: 1c962069-7ced-4162-a11f-acb40fd954f4 (external_ip), ip: 198.51.100.3 }) } conflicts with existing: [OmicronZoneExternalIpEntry { zone_id: 34feb176-1129-4ca8-8df8-6e6cb1be2173 (service), ip: Floating(OmicronZoneExternalFloatingIp { id: 1b31bc81-c2ef-4915-be62-c97bd7881b07 (external_ip), ip: 198.51.100.3 }) }]
```

Fixes #7305