Show example cycle when ls-apis errors about them
`cargo xtask ls-apis check` will report an error if the software
component graph contains a cycle, as well as if the deployment units
form a cycle, but prints only the name of a node in the graph that was
in the cycle. If you've added a cycle to either of these graphs, the
error and node can tell you about the what that is wrong. Going a bit
further and printing an example cycle including the troublesome node can
help with the how you got there.

With this change, the first approach at #10231 (which introduced a cycle
in, but all in one deployment unit: sled-agent -> propolis-server ->
sled-agent) errors with a more clear message about propolis-server and
sled-agent being the problems:

```
Error: graph of server-managed API dependencies between components has a cycle
(includes node: "propolis-server", example cycle: propolis-server, omicron-sled-agent)
```