EarlyNetworkSetupError: stop duplicate log output on DnsResolver variant
Similar to the last commit, this updates the #[error(...)] attribute on
the DnsResolver variant on EarlyNetworkSetupError, to avoid recursing
into the Display implementation of ResolveError.

All callers appear to be handling EarlyNetworkSetupError correctly
already, so this commit doesn't make any other changes.