Move SWITCH_ZONE_BASEBOARD_FILE to sled-agent-types (#7669)
This allows us to remove the dependency on sled-agent in zone-setup,
which is pulled in for a single type definition.

Without this change a debug build currently relies on libnvme.so, while
the compiler is able to elide this library on a release build:
```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4m 14s
Error: Found library issues with the following:
nexus
        UNEXPECTED dependency on libsqlite3.so.0
omicron-dev
        UNEXPECTED dependency on libsqlite3.so.0
zone-setup
        NEEDS libnvme.so.1 but is not allowed


If depending on a new library was intended please add it to xtask.toml

```

And after this change we no longer depend on it in debug/release builds:
```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 10s
Error: Found library issues with the following:
nexus
        UNEXPECTED dependency on libsqlite3.so.0
omicron-dev
        UNEXPECTED dependency on libsqlite3.so.0


If depending on a new library was intended please add it to xtask.toml
```