Add static assertion for latest `WriteNetworkConfigRequest` alias (#10930)
This is followup from
https://github.com/oxidecomputer/omicron/pull/10572#discussion_r3658799347:
on that PR, we added a new `WriteNetworkConfigRequest` type for a
bootstore bump, but didn't add a corresponding new sled-agent API to
handle it, and there were no compile time or test time failures to point
out the oversight.

The sled-agent API intentionally and explicitly does not use the
`latest` alias for reasons explained in a long block comment; this PR
extends that block comment and adds a static assertion checking that
`latest` points to a specific version. This will have to be kept in sync
manually when adding new bootstore type versions; I _think_ that's
acceptable overhead, is better than silently allowing the wrong thing,
and I'm not sure how to make this easier without introducing similar
footguns as those we're trying to avoid.

If I patch this onto #10572 in its current state, I get this compilation
error:

```
error: could not compile `sled-agent-api` (lib) due to 1 previous error
error[E0271]: type mismatch resolving `<WriteNetworkConfigRequest as TypeEq>::This == WriteNetworkConfigRequest`
   --> sled-agent/api/src/lib.rs:965:13
    |
965 |             v42::system_networking::WriteNetworkConfigRequest,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type mismatch resolving `<WriteNetworkConfigRequest as TypeEq>::This == WriteNetworkConfigRequest`
    |
note: expected this to be `sled_agent_types_versions::latest::system_networking::WriteNetworkConfigRequest`
   --> sled-agent/api/src/lib.rs:964:9
    |
964 | /         static_assertions::assert_type_eq_all!(
965 | |             v42::system_networking::WriteNetworkConfigRequest,
966 | |             latest::system_networking::WriteNetworkConfigRequest
967 | |         );
    | |_________^
note: required by a bound in `assert_type_eq_all`
   --> sled-agent/api/src/lib.rs:964:9
    |
964 | /         static_assertions::assert_type_eq_all!(
965 | |             v42::system_networking::WriteNetworkConfigRequest,
966 | |             latest::system_networking::WriteNetworkConfigRequest
967 | |         );
    | |         ^
    | |         |
    | |_________required by a bound in this function
    |           required by this bound in `assert_type_eq_all`
    = note: this error originates in the macro `static_assertions::assert_type_eq_all` (in Nightly builds, run with -Z macro-backtrace for more info)
```

which hopefully sticks out enough that we know to (a) bump that v42 to
v43 and (b) read the attached comment and add a
`write_network_bootstore_config_v43()` endpoint.