oxide/opte-interface-setup should default to disabled (#5230)
The `oxide/opte-interface-setup` service is present in all NTP zones,
but only the boundary zones require an OPTE interface. sled-agent
explicitly enables the service for just the boundary zones, but because
the service is enabled by default it ends up attempting to start in the
non-boundaries too, where it fails.

```
[ Mar  8 12:56:26 Executing start method ("/opt/oxide/zone-network-cli/bin/zone-networking opte-interface-set-up -i unknown -g unknown -p unknown"). ]
note: configured to log to "/dev/stderr"
error: invalid value 'unknown' for '--opte_interface <STRING>': ERROR: Missing OPTE interface

For more information, try '--help'.
[ Mar  8 12:56:26 Method "start" exited with status 2. ]
```