wicket: Deny unknown fields when accepting RSS config TOML (#7667)
From discussions on #7653: wicket does not and should not accept a
`[recovery_silo]` section in the uploaded TOML, but on main it will
silently discard it. This PR turns on `serde(deny_unknown_fields)`; now,
attempting to upload a config TOML with an unexpected section will fail:

```
Feb 27 16:44:21.805 INFO reading config from stdin..., file: wicket/src/cli/rack_setup.rs:110
Feb 27 16:44:21.805 INFO parsing config..., file: wicket/src/cli/rack_setup.rs:115
Error: failed to parse config TOML

Caused by:
    TOML parse error at line 93, column 2
       |
    93 | [recovery_silo]
       |  ^^^^^^^^^^^^^
    unknown field `recovery_silo`, expected one of `bootstrap_sleds`, `ntp_servers`, `dns_servers`, `internal_services_ip_pool_ranges`, `external_dns_ips`, `external_dns_zone_name`, `rack_network_config`, `allowed_source_ips`
```